# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_sw.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_auto_sw(object):
    def setupUi(self, auto_sw):
        auto_sw.setObjectName("auto_sw")
        auto_sw.resize(266, 182)
        self.target_comboBox = QtWidgets.QComboBox(auto_sw)
        self.target_comboBox.setGeometry(QtCore.QRect(20, 20, 231, 22))
        self.target_comboBox.setObjectName("target_comboBox")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.freqency_tabWidget = QtWidgets.QTabWidget(auto_sw)
        self.freqency_tabWidget.setGeometry(QtCore.QRect(20, 50, 231, 91))
        self.freqency_tabWidget.setObjectName("freqency_tabWidget")
        self.hourly_tab = QtWidgets.QWidget()
        self.hourly_tab.setObjectName("hourly_tab")
        self.hourly_spinBox = QtWidgets.QSpinBox(self.hourly_tab)
        self.hourly_spinBox.setGeometry(QtCore.QRect(110, 20, 42, 22))
        self.hourly_spinBox.setMaximum(59)
        self.hourly_spinBox.setObjectName("hourly_spinBox")
        self.hourly_label = QtWidgets.QLabel(self.hourly_tab)
        self.hourly_label.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.hourly_label.setObjectName("hourly_label")
        self.freqency_tabWidget.addTab(self.hourly_tab, "")
        self.daily_tab = QtWidgets.QWidget()
        self.daily_tab.setObjectName("daily_tab")
        self.daily_timeEdit = QtWidgets.QTimeEdit(self.daily_tab)
        self.daily_timeEdit.setGeometry(QtCore.QRect(100, 20, 111, 22))
        self.daily_timeEdit.setObjectName("daily_timeEdit")
        self.daily_label = QtWidgets.QLabel(self.daily_tab)
        self.daily_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.daily_label.setObjectName("daily_label")
        self.freqency_tabWidget.addTab(self.daily_tab, "")
        self.weekly_tab = QtWidgets.QWidget()
        self.weekly_tab.setObjectName("weekly_tab")
        self.weekly_comboBox = QtWidgets.QComboBox(self.weekly_tab)
        self.weekly_comboBox.setGeometry(QtCore.QRect(100, 10, 69, 22))
        self.weekly_comboBox.setObjectName("weekly_comboBox")
        self.weekly_comboBox.addItem("")
        self.weekly_comboBox.addItem("")
        self.weekly_comboBox.addItem("")
        self.weekly_comboBox.addItem("")
        self.weekly_comboBox.addItem("")
        self.weekly_comboBox.addItem("")
        self.weekly_comboBox.addItem("")
        self.weekly_day_label = QtWidgets.QLabel(self.weekly_tab)
        self.weekly_day_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.weekly_day_label.setObjectName("weekly_day_label")
        self.weekly_timeEdit = QtWidgets.QTimeEdit(self.weekly_tab)
        self.weekly_timeEdit.setGeometry(QtCore.QRect(100, 40, 111, 22))
        self.weekly_timeEdit.setObjectName("weekly_timeEdit")
        self.weekly_time_label = QtWidgets.QLabel(self.weekly_tab)
        self.weekly_time_label.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.weekly_time_label.setObjectName("weekly_time_label")
        self.freqency_tabWidget.addTab(self.weekly_tab, "")
        self.monthly_tab = QtWidgets.QWidget()
        self.monthly_tab.setObjectName("monthly_tab")
        self.monthly_day_label = QtWidgets.QLabel(self.monthly_tab)
        self.monthly_day_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.monthly_day_label.setObjectName("monthly_day_label")
        self.monthly_spinBox = QtWidgets.QSpinBox(self.monthly_tab)
        self.monthly_spinBox.setGeometry(QtCore.QRect(110, 10, 42, 22))
        self.monthly_spinBox.setMinimum(1)
        self.monthly_spinBox.setMaximum(29)
        self.monthly_spinBox.setObjectName("monthly_spinBox")
        self.monthly_timeEdit = QtWidgets.QTimeEdit(self.monthly_tab)
        self.monthly_timeEdit.setGeometry(QtCore.QRect(110, 40, 101, 22))
        self.monthly_timeEdit.setObjectName("monthly_timeEdit")
        self.monthly_time_label = QtWidgets.QLabel(self.monthly_tab)
        self.monthly_time_label.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.monthly_time_label.setObjectName("monthly_time_label")
        self.freqency_tabWidget.addTab(self.monthly_tab, "")
        self.createauto_pushButton = QtWidgets.QPushButton(auto_sw)
        self.createauto_pushButton.setGeometry(QtCore.QRect(180, 150, 75, 23))
        self.createauto_pushButton.setObjectName("createauto_pushButton")

        _translate = QtCore.QCoreApplication.translate
        auto_sw.setWindowTitle(_translate("auto_sw", "Auto-Collector Setup"))
        self.target_comboBox.setItemText(0, _translate("auto_sw", "user1"))
        self.target_comboBox.setItemText(1, _translate("auto_sw", "user2"))
        self.hourly_label.setText(_translate("auto_sw", "Minute on the hour:"))
        self.freqency_tabWidget.setTabText(self.freqency_tabWidget.indexOf(
            self.hourly_tab), _translate("auto_sw", "Hourly"))
        self.daily_label.setText(_translate("auto_sw", "Time on the day:"))
        self.freqency_tabWidget.setTabText(self.freqency_tabWidget.indexOf(
            self.daily_tab), _translate("auto_sw", "Daily"))
        self.weekly_comboBox.setItemText(0, _translate("auto_sw", "Sunday"))
        self.weekly_comboBox.setItemText(1, _translate("auto_sw", "Monday"))
        self.weekly_comboBox.setItemText(2, _translate("auto_sw", "Tuesday"))
        self.weekly_comboBox.setItemText(3, _translate("auto_sw", "Wednesday"))
        self.weekly_comboBox.setItemText(4, _translate("auto_sw", "Thursday"))
        self.weekly_comboBox.setItemText(5, _translate("auto_sw", "Friday"))
        self.weekly_comboBox.setItemText(6, _translate("auto_sw", "Saturday"))
        self.weekly_day_label.setText(
            _translate("auto_sw", "Day of the week:"))
        self.weekly_time_label.setText(
            _translate("auto_sw", "Time on the day:"))
        self.freqency_tabWidget.setTabText(self.freqency_tabWidget.indexOf(
            self.weekly_tab), _translate("auto_sw", "Weekly"))
        self.monthly_day_label.setText(
            _translate("auto_sw", "Day of the month:"))
        self.monthly_time_label.setText(
            _translate("auto_sw", "Time on the day:"))
        self.freqency_tabWidget.setTabText(self.freqency_tabWidget.indexOf(
            self.monthly_tab), _translate("auto_sw", "Monthly"))
        self.createauto_pushButton.setText(_translate("auto_sw", "Create"))
        self.freqency_tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(auto_sw)
